# apr_user:
    # resource: "@APRUserBundle/Resources/config/routing.yml"
    # prefix:   /

apr_site:
    resource: "@APRSiteBundle/Resources/config/routing.yml"
    prefix:   /


# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

fos_user_security:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"
   prefix: /fossecurity
 
fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /profile

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profile